### ISSUE TITLE
encode frames by av1

### ISSUE THREAD

**Issue by PooyaEimandar** [WolfEngine/WolfEngine#161]
We need to migrate to AV1, the latest royalty-free video coding format for video transmissions over the Internet.
For streamer we can use [rav1e](https://github.com/xiph/rav1e).

**Comment by SiminBadri** [comment]
In this issue, the images should be encoded using the `av1` library. 

To implement `av1`, there are 3 libraries:

- [`AOM`](https://github.com/luctrudeau/libaom)

- [`rav1e`](https://github.com/xiph/rav1e)

- [`svt-av1`](https://github.com/AOMediaCodec/SVT-AV1)

To compare these libraries, I use the `ffmpeg` library. For each test, I built the `ffmpeg` with one of the above libraries and used the same code for encoding and decoding the images. I compared the outputs in terms of encoding time, decoding time, and the size of the encoded file. The result of this comparison is attached in the following. Regarding this result, we decided to use `svt-av1` library through the `ffmpeg` library.

[AV1-Benchmark.pdf](https://github.com/WolfEngine/WolfEngine/files/8990257/AV1-Benchmark.pdf)
