### ISSUE TITLE
Make time.rs work on WASM

### ISSUE THREAD

**Issue by PooyaEimandar** [WolfEngine/WolfEngine#239]
Currently [time.rs](https://github.com/WolfEngine/WolfEngine/blob/main/wolf/src/system/chrono/time.rs) works just on Native platforms, we need to support Wasm platform as well.

**Comment by MaryamRezaeiBarzi** [comment]
آقای @PooyaEimandar لطفا آقای شریفی را به این ایشو اساین بفرمایید.
