### ISSUE TITLE
build RIST for android

### ISSUE THREAD

**Issue by PooyaEimandar** [WolfEngine/WolfEngine#392]
build and [test RIST](https://github.com/WolfEngine/WolfEngine/tree/main/wolf/stream/test) for android architectures:

- [x] armv7a
- [x] armv8a
- [x] arm64

**Comment by SiminBadri** [comment]
LibRist library is built for android successfully. Note that building for architectures "armv8a" and "arm64" is provided in one common build target "arm64".
