### ISSUE TITLE
make cmake config usable as external dependency

### ISSUE THREAD

**Issue by cthulhu-irl** [WolfEngine/WolfEngine#419]
current cmake config is not suitable to be used externally. (via `add_subdirectory`)

**Comment by PooyaEimandar** [comment]
[this CMake](https://github.com/WolfEngine/WolfEngine/blob/main/CMakeLists.txt) will be used for managing examples/demos/editor as well as the core of wolf.
If you want to link wolf as a stand-alone library to your project, please use [this CMake](https://github.com/WolfEngine/WolfEngine/tree/main/wolf).
