### ISSUE TITLE
initiate msquic wrapper library development

### ISSUE THREAD

**Issue by cthulhu-irl** [WolfEngine/WolfEngine#466]
Initiate and add msquic wrapper library development in stream module.

This issue is only to get the library development deps and base initiatives started as a base ground for its further step by step development.

**Comment by cthulhu-irl** [comment]
vcpkg PR to add msquic v2.2 is in progress: https://github.com/microsoft/vcpkg/pull/29568

using fetchcontent with source code leads to really long and failing process of fetching its deep nested submodules. simply unfeasible.

@PooyaEimandar, how do recommend to proceed?

I'd suggest using pre-built binaries (downloaded via FetchContent from msquic's released packages in github) windows-only until v2.2 is added to vcpkg.

**Comment by PooyaEimandar** [comment]
> vcpkg PR to add msquic v2.2 is in progress: https://github.com/microsoft/vcpkg/pull/29568
> 
> using fetchcontent with source code leads to really long and failing process of fetching its deep nested submodules. simply unfeasible.
> 
> @PooyaEimandar, how do recommend to proceed?
> 
> I'd suggest using pre-built binaries (downloaded via FetchContent from msquic's released packages in github) windows-only until v2.2 is added to vcpkg.

Sounds good
